### ISSUE TITLE
XSLT 1.0 Compatibility

### ISSUE THREAD

**Issue by martinklepsch** [eerohele/sigel#1]
Saxon had some releases where it deprecated XSLT 1.0 but since reverted that change: https://stackoverflow.com/questions/45595852/xtde0160-xslt-1-0-compatibility-mode-is-not-available-in-this-configuration-in

I manually bumped Saxon to `net.sf.saxon/Saxon-HE {:mvn/version "9.8.0-14"}` and it all worked fine again. Might be worth cutting a new release bumping Saxon. :) 

EDIT: Nice API docs! 😊

**Comment by eerohele** [comment]
Thanks for the report!

I've cut 0.2.1, which should fix XSLT 1.0 compatibility. Can you give it a shot and let me know whether it works?

>EDIT: Nice API docs! 

Thanks! Good tooling works wonders.

**Comment by martinklepsch** [comment]
Works perfectly, thanks!
