### ISSUE TITLE
Cyrillic letters in a call to match produces an error

### ISSUE THREAD

**Issue by akond** [eerohele/sigel#3]
as long as i use latin letters everything's fine, but when i put, for instance,
`(xsl/template {:match "para[matches(., 'Пам')]"} ...` i immediatelly get this error

> Caused by: org.xml.sax.SAXParseException: An invalid XML character (Unicode: 0x1f) was found in the value of attribute "match" and element is "xsl:template".

i wander what could be the problem?

**Comment by eerohele** [comment]
This happened because I had used the deprecated `java.io.StringBufferInputStream` class in code that converts a string to a `StreamSource`.

This should be fixed in v0.2.3. Can you give it a go and let me know whether it fixes the issue for you?

**Comment by akond** [comment]
Yeah, 0.2.3 does the job.
Thank you very much.

**Comment by eerohele** [comment]
Glad to hear it. Many thanks for reporting the issue and getting back to me.
