### ISSUE TITLE
CDATA

### ISSUE THREAD

**Issue by akond** [eerohele/sigel#5]
I use `(xsl/output {:method "text"})` to produce a text file and I can't seem to find a way to produce the `>` char. I always get `&gt;` instead. Am I missing anything?

**Comment by eerohele** [comment]
Ah. This is related to how clojure.data.xml [serializes things](https://github.com/clojure/data.xml#examples).

I figured this should work:

```clojure
(->
    (xsl/stylesheet {:version 3.0}
      (xsl/output {:method "text"})
      (xsl/template {:match "a"}
        [:b
         [:-cdata ">"]]))
    (compile-sexp)
    (transform "<a/>"))
```

But it doesn't.

I'll have to dig into it, but I'll be honest and say that I'm so swamped with other work that I don't know when I'll be able to get to it.

**Comment by akond** [comment]
It turns out that Saxon doesn't support > and < inside CDATA and converts them into corresponding html entities.

**Comment by eerohele** [comment]
Sorry, forgot about this one for a while. Is this still an issue?

**Comment by akond** [comment]
I found a workaround. And since this is a Saxon's issue, I assume this issue can be closed.

**Comment by eerohele** [comment]
Cool, thanks for the info. 👍🏻
